name: Build Linux Kernel and pack
on:
  workflow_dispatch:
    inputs:
      build_clean_ccache:
        description: 'with ccache or not'
        required: true
        default: true
        type: boolean
      branch:
        description: 'Branch to checkout'
        required: true
        default: 'master'
        type: string
  
jobs:
  buildNPack:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-24.04-arm]
        architecture: [arm64]

    steps:
      - name: Checkout another repo
        uses: actions/checkout@v4
        with:
          repository: bugparty/cs251_kernel
          token: ${{ secrets.REPO_PAT }}
          ref: ${{ github.event.client_payload.branch || github.event.inputs.branch }}

      - name: Print runner machine size
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner Architecture: ${{ runner.arch }}"
          echo "Runner Name: ${{ runner.name }}"
          echo "Runner Temp Directory: ${{ runner.temp }}"
          echo "Runner Workspace Directory: ${{ runner.workspace }}"
          echo "Runner CPU Cores: `nproc`"

      - name: ls Directory
        run: ls -l
      - name: Set up ARM64 GCC cross-compile toolchain
        if: matrix.architecture == 'x64'
        run: |
          sudo apt-get update
          sudo apt-get install -y exuberant-ctags crossbuild-essential-arm64 
      - name: Set up native ARM64 toolchain
        if: matrix.architecture == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y exuberant-ctags build-essential
      - name: Set build_clean_ccache for pull request
        if: github.event_name == 'pull_request'
        run: echo "build_clean_ccache=true" >> $GITHUB_ENV
      - name: Print enable_feature value
        run: |
          if [[ -z "${{ github.event.inputs.build_clean_ccache }}" && -z "${{ env.build_clean_ccache }}" ]]; then
            echo "build_clean_ccache=true" >> $GITHUB_ENV
          else
            echo "build_clean_ccache=${{ github.event.inputs.build_clean_ccache || env.build_clean_ccache }}" >> $GITHUB_ENV
          fi
          echo "build_clean_ccache: ${{ env.build_clean_ccache }}"
        
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
          max-size: "800M"
          restore: ${{ env.build_clean_ccache }}

      - name: compile kernel
        run: |
          chmod +x compile_w_ccache.sh
          ./compile_w_ccache.sh
      - name: build project 1
        run: |
          cd proj1
          chmod +x compile.sh
          ./compile.sh
      - name: pack linux kernel
        run: |
          ./pack.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-and-projects
          path: |
            proj1/apps/hello/usrhello
            proj1/apps/test_count_tasks/test_count_tasks
            proj1/modules/mod_count_tasks/mod_count_tasks.ko
            kernel.tgz

